### ISSUE TITLE
Ropsten Oracle does not write data back to chain

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [smartcontractkit/chainlink#602]
### System Information

- Network (Main net, Ropsten, etc.):  Ropsten
- Ethereum client (Geth/Parity) and version: Metamask
- Go version: N/A
- Host OS: OS X 10.13.4
- Commit (INFO line when starting the node): 

### Environment Variables

N/A

### Additional Information

Ropsten Oracle does not write data back to chain

- Spec:

Uint256 job

- Oracle contract address: 0x18170370BceC331F31d41B9b83DE772F5Bd47D82
- Transaction ID: https://ropsten.etherscan.io/tx/0xc049e1c15527cf0d3fc30dcdccad845c5416d1b1d881a9d54df99f0ae65f72ef#eventlog

**Comment by thodges-gh** [comment]
@Xuefeng-Zhu this should be resolved now when using the Job Specs from [here](https://docs.chain.link/v1.0/docs/getting-started#section-job-specs). I also have https://github.com/smartcontractkit/chainlink/pull/604 up to resolve this for RopstenConsumer.sol. Can you try again and let me know, please? Thank you!

**Comment by Xuefeng-Zhu** [comment]
@thodges-gh Thank you for the quick response. I actually tried the job id in https://docs.chain.link/v1.0/docs/getting-started#section-job-specs, but it is still not working correctly for me. I tried the one for Rinkeby, and it is working fine

**Comment by Xuefeng-Zhu** [comment]
@thodges-gh I tried the contract on ropsten again today, and it seems to work fine

**Comment by thodges-gh** [comment]
@Xuefeng-Zhu good to hear. Thanks for letting us know!
